### ISSUE TITLE
Inaccurate comment in auto-generated docker-compose.yml file

### ISSUE THREAD

**Issue by deivamagalhaes** [bryangruneberg/laragoon#8]
Hello,

I've noticed the comment needs to be updated on this line:

https://github.com/bryangruneberg/laragoon/blob/c88ab9ce5f0ab7c45498e33629490b1980b2a91a/docker/php-7.2/docker-compose.yml#L2

Cheers!

Deiva

**Comment by bryangruneberg** [comment]
Fixed :D
