### ISSUE TITLE
Incorrect Maria DB username variable generated

### ISSUE THREAD

**Issue by carloshmiranda** [bryangruneberg/laragoon#9]
The script create env as MARIADB_USER, instead of MARIADB_USERNAME

**Comment by bomoko** [comment]
Assigning this to myself. Will fix it tonight.

**Comment by bomoko** [comment]
@carloshmiranda This should already be fixed (see https://github.com/bryangruneberg/laragoon/pull/5/files)

**Comment by carloshmiranda** [comment]
Great, thanks.
